menu:
  home: Home
  blog: Blog
  repositories: Repositories
  about: About
  contact: Contact
  archive: Archive
footer:
  feed: Feed
  imprint: Imprint
  privacy-policy: Privacy Policy
navigation:
  toggle: Toggle Navigation
  older: Older
  newer: Newer
pagination:
  previous: Previous
  next: Next
search:
  title: Search
  placeholder: Type something...
  posts: Posts
  pages: Pages
  categories: Categories
  tags: Tags
  untitled: (Untitled)
sidebar:
  widget:
    announcement: announcement
    archive: archive
    tags: tags
    categories: categories
    tagCloud: tag cloud
    recentPosts: latest articles
copyright:
  theme_by: Theme by
  based_on: based on
  powered_by: Powered by
