# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
## https://hexo.io/docs/configuration#Site
title: Hannes Leutloff - yeldiRium
description: 'Personal blog about stuff.'
keywords:
author: Hannes Leutloff
language: en
timezone: Europe/Berlin

# URL
## https://hexo.io/docs/configuration#URL
url: https://yeldirium.de
root: /
permalink: :year/:month/:day/:title/
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
## https://hexo.io/docs/configuration#Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archive
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
## https://hexo.io/docs/configuration#Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: []
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: false
highlight:
  enable: false

# Home page setting
## https://hexo.io/docs/configuration#Home-page-setting
index_generator:
  path: '/blog'
  per_page: 10
  order_by: -date
  pagination_dir:

# Category & Tag
## https://hexo.io/docs/configuration#Category-amp-Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## https://hexo.io/docs/configuration#Date-Time-format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
use_date_for_updated: false

# Extensions
## https://hexo.io/docs/configuration#Extensions
theme: yeldirium
theme_config:
deploy:
meta_generator: true

## Plugins: https://hexo.io/plugins/
## https://github.com/hexojs/hexo-generator-archive
archive_generator:
  enabled: true
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  order_by: -date
## https://github.com/hexojs/hexo-generator-tag
tag_generator:
  per_page: 10
  order_by: -date
## https://github.com/hexojs/hexo-generator-category
category_generator:
  per_page: 10
  order_by: -date
## https://github.com/ele828/hexo-prism-plugin
prism_plugin:
  mode: 'preprocess'
  theme: 'default'
  line_number: false
## https://github.com/alexbruno/hexo-generator-json-content
jsonContent:
  ignore:
    paths:
      - 404.html
      - archive/
      - blog/
      - meta/imprint.html
      - meta/privacy-policy.html
## https://github.com/hexojs/hexo-generator-feed
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content: false
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  autodiscovery: true
