# html lang
language: en

# main menu navigation
menu:
  - name: home
    path: /
    icon: fas fa-w-18 fa-home
    enabled: true
  - name: blog
    path: /blog/
    icon: fas fa-w-18 fa-align-left
    enabled: true
  - name: repositories
    path: /repositories/
    icon: fas fa-w-18 fa-folder
    enabled: false
  - name: about
    path: /about/
    icon: fas fa-w-18 fa-user
    enabled: true
  - name: contact
    path: /contact/
    icon: fas fa-w-18 fa-address-book
    enabled: true
  - name: archive
    path: /archive/
    icon: fas fa-w-18 fa-archive
    enabled: true

footer:
  - name: imprint
    path: /meta/imprint.html
    enabled: true
  - name: privacy-policy
    path: /meta/privacy-policy.html
    enabled: true

site:
  favicon: /favicon.ico
  showProfileInHeader: true
  enableMenuIcons: true
  announcement:
  archive:
    showCount: true
    type: yearly
  categories:
    showCount: true
  tags:
    showCount: true
  tagCloud:
    minFont: 13
    maxFont: 14
  pagination:
    prev:
      alwayShow: true
    next:
      alwayShow: true

profile:
  gravatar:
  avatar: /assets/images/hannes-leutloff-2017-128x128.png
  author: Hannes Leutloff
  author_title: Software Engineer
  location: Neu-Isenburg, Germany
  social:
    names:
      github: yeldiRium
    links:
      github: https://github.com/yeldiRium
      twitter: https://twitter.com/yeldiRium
      linkedin: https://www.linkedin.com/in/hannes-leutloff/

sidebar:
  enabled: true
  widgets:
    #- announcement
    - recentPosts
    - archive
    - tagCloud
    - categories
